#!/bin/sh
#
# All commit messages follow Magento commit requirements

if !(echo `cat "$1"` | grep -Eq "(^[[:alpha:]]+-[[:digit:]]+):[[:space:]](\[|[[:alpha:]])+"); then
        echo "[MAGENTO POLICY] Wrong commit message"
        exit 1
fi
